// User Action Types
export const user = {
  LOG_IN_LOADING: 'LOG_IN_LOADING',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',

  LOG_OUT_LOADING: 'LOG_OUT_LOADING',
  LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
};

// Project Action Types
export const project = {
  GET_ALL_PROJECTS_LOADING: 'GET_ALL_PROJECTS_LOADING',
  GET_ALL_PROJECTS_FAILURE: 'GET_ALL_PROJECTS_FAILURE',
  GET_ALL_PROJECTS_SUCCESS: 'GET_ALL_PROJECTS_SUCCESS',

  GET_PROJECT_LOADING: 'GET_PROJECT_LOADING',
  GET_PROJECT_FAILURE: 'GET_PROJECT_FAILURE',
  GET_PROJECT_SUCCESS: 'GET_PROJECT_SUCCESS',

  CREATE_PROJECT_LOADING: 'CREATE_PROJECT_LOADING',
  CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
  CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',

  DELETE_PROJECT_LOADING: 'DELETE_PROJECT_LOADING',
  DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
};

// Metric Action Types
export const metric = {
  GET_ALL_METRICS_LOADING: 'GET_ALL_METRICS_LOADING',
  GET_ALL_METRICS_FAILURE: 'GET_ALL_METRICS_FAILURE',
  GET_ALL_METRICS_SUCCESS: 'GET_ALL_METRICS_SUCCESS',

  CREATE_METRIC_LOADING: 'CREATE_METRIC_LOADING',
  CREATE_METRIC_FAILURE: 'CREATE_METRIC_FAILURE',
  CREATE_METRIC_SUCCESS: 'CREATE_METRIC_SUCCESS',

  GET_METRIC_LOADING: 'GET_METRIC_LOADING',
  GET_METRIC_FAILURE: 'GET_METRIC_FAILURE',
  GET_METRIC_SUCCESS: 'GET_METRIC_SUCCESS',

  DELETE_METRIC_LOADING: 'DELETE_METRIC_LOADING',
  DELETE_METRIC_FAILURE: 'DELETE_METRIC_FAILURE',
  DELETE_METRIC_SUCCESS: 'DELETE_METRIC_SUCCESS',
}

// Page Selection
export const currentPage = {
  PAGE_CHANGED: 'PAGE_CHANGED',
};
