// User Action Types
export const user = {
    LOG_IN_LOADING: "LOG_IN_LOADING",
    LOG_IN_FAILURE: "LOG_IN_FAILURE",
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",

    LOG_OUT_LOADING: "LOG_OUT_LOADING",
    LOG_OUT_FAILURE: "LOG_OUT_FAILURE",
    LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
}

// Project Action Types
export const project = {
    GET_ALL_PROJECTS_LOADING: "GET_ALL_PROJECTS_LOADING",
    GET_ALL_PROJECTS_FAILURE: "GET_ALL_PROJECTS_FAILURE",
    GET_ALL_PROJECTS_SUCCESS: "GET_ALL_PROJECTS_SUCCESS",

    GET_PROJECT_LOADING: "GET_PROJECT_LOADING",
    GET_PROJECT_FAILURE: "GET_PROJECT_FAILURE",
    GET_PROJECT_SUCCESS: "GET_PROJECT_SUCCESS",

    CREATE_PROJECT_LOADING: "CREATE_PROJECT_LOADING",
    CREATE_PROJECT_FAILURE: "CREATE_PROJECT_FAILURE",
    CREATE_PROJECT_SUCCESS: "CREATE_PROJECT_SUCCESS",

    DELETE_PROJECT_LOADING: "DELETE_PROJECT_LOADING",
    DELETE_PROJECT_FAILURE: "DELETE_PROJECT_FAILURE",
    DELETE_PROJECT_SUCCESS: "DELETE_PROJECT_SUCCESS",
}

// Page Selection
export const currentPage = {
    PAGE_CHANGED: "PAGE_CHANGED",
}

